#!/usr/bin/env tsx
/**
 * Emits `[data-theme="light"]` / `[data-theme="dark"]` CSS custom-property blocks
 * from the TS token source (categories.ts + chrome.ts) so web's globals.css and
 * this package's TS exports can never drift apart — one source, two consumers.
 *
 * Usage: tsx scripts/generateCssVars.ts [outputPath]
 * Defaults to stdout when no outputPath is given.
 */
import { writeFileSync } from "node:fs";
import { CATEGORY_COLORS } from "../src/categories";
import { CHROME, STATUS_COLORS } from "../src/chrome";
import { hexToRgbTriple } from "../src/hex";

function block(mode: "light" | "dark"): string {
  const lines: string[] = [];
  for (const [key, color] of Object.entries(CATEGORY_COLORS)) {
    lines.push(`  --category-${key}-rgb: ${hexToRgbTriple(color[mode])};`);
  }
  for (const [key, color] of Object.entries(CHROME)) {
    const kebab = key.replace(/([A-Z])/g, "-$1").toLowerCase();
    lines.push(`  --chrome-${kebab}-rgb: ${hexToRgbTriple(color[mode])};`);
  }
  for (const [key, color] of Object.entries(STATUS_COLORS)) {
    lines.push(`  --status-${key}-rgb: ${hexToRgbTriple(color[mode])};`);
  }
  return `[data-theme="${mode}"] {\n${lines.join("\n")}\n}`;
}

function generateCss(): string {
  return [
    "/* AUTO-GENERATED by packages/ui-tokens/scripts/generateCssVars.ts — do not edit by hand. */",
    block("light"),
    block("dark"),
    "",
  ].join("\n\n");
}

function main() {
  const css = generateCss();
  const outPath = process.argv[2];
  if (outPath) {
    writeFileSync(outPath, css, "utf-8");
    console.log(`Wrote ${outPath}`);
  } else {
    console.log(css);
  }
}

main();
